### ISSUE TITLE
How to run a demo or a test?

### ISSUE THREAD

**Issue by zeroRains** [lynn2089/SmartLite#1]
Hi, I have seen the README say that `All test_x_in_db.py files are the experiments used to measure the performance of SmartLite based on different datasets (CIFAR10/ImageNet/MNIST)`.  I looked the file `test_cifar10_in_db.py`，I found it without any code about the db in the main. I try to use the `m4_conv`, `m4_pool` and `m4_linear` in the main, but there is no file named `m2_linear_cifar10_height.npy` and `m2_linear_cifar10_weight.npy`. it can not run.

I want to know how to get this file?

Is this file can run a DL model to infer a result?

Thanks for your help.

ps: I have deployed a click_house db in my computer.

**Comment by lynn2089** [comment]
Hello, the .npy file is a temporary file used to store the weight data of the neural network (just for the convenience of testing), so we did not make it public. Such files can be retrained and generated. First, you can train a model in a data set. Secondly, you can convert the data according to the format of the data stored in the database in Section 3 of the paper (which has been explained in great detail, you can refer to the image provided in the paper). The converted data is stored in npy files. The steps of conversion include: 1. Quantization; 2, weight for bitwise storage (note that the corresponding position should be correct)

**Comment by zeroRains** [comment]
Hi! Maybe I can run the command `python main_binary.py --model resnet_binary --save resnet18_binary --dataset cifar10` to get a model. But I found it only saved a conv layer weight. If I want to save the whole network parameter, I will use the `torch.save()` to get a `.pth` file rather than the `.npy` file. Is there any transform method to do it?

**Comment by lynn2089** [comment]
You can save the parameters of each layer of the neural network(e.g., Conv), read the values of each position, and save these parameters as a new .npy file according to the data structure presented in the paper.
